AWSTemplateFormatVersion: '2010-09-09'
Description: Test cfn Template

Resources:
  cfnVpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '192.168.0.0/16'
      Tags:
        - Key: 'Name'
          Value: 'yano-test-vpc'
  cfnSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: '192.168.1.0/24'
      MapPublicIpOnLaunch: true
      Tags:
         - Key: 'Name'
           Value: 'yano-test-subnet'
      VpcId: !Ref cfnVpc
  cfnInternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'yano-test-internet-gateway'
  cfnAttachGateWay:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref cfnInternetGateway
      VpcId: !Ref cfnVpc
  cfnRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref cfnVpc
      Tags:
        - Key: 'Name'
          Value: 'yano-test-route-table'
  cfnRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref cfnInternetGateway
      RouteTableId: !Ref cfnRouteTable
  cfnSubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref cfnRouteTable
      SubnetId: !Ref cfnSubnet
  cfnEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0964d004dc4ffafc1'
      InstanceType: 't2.micro'
      SubnetId: !Ref cfnSubnet
      BlockDeviceMappings:
        - DeviceName: '/dev/xvda'
          Ebs:
            VolumeType: 'gp2'
            VolumeSize: '8'
      Tags:
        - Key: 'Name'
          Value: 'yano-test-from-cloud-formation'
      SecurityGroupIds:
        - !Ref cfnSecurityGroup
  cfnSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'yano-test-security-group'
      VpcId: !Ref cfnVpc
      Tags:
        - Key: 'Name'
          Value: 'yano-test-ssh-sg'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
